# Generated by Django 3.1.3 on 2020-12-01 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201201_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.departamento'),
            preserve_default=False,
        ),
    ]
